"""add user_token and token_created_at to user

Revision ID: 21924fe5f860
Revises: 
Create Date: 2025-11-01 21:06:40.079830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21924fe5f860'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_token', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('token_created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['user_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token_created_at')
        batch_op.drop_column('user_token')

    # ### end Alembic commands ###
